version: '3'
services:
  app:
    build: .
    container_name: QickStudy
    ports:
      - 8000:8080
    depends_on:
      - mysql
    environment:
      - FLASK_MODE=ProductionEnv
    networks:
      - qick

  mysql:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qickstudy
      - MYSQL_USER=qickstudy
      - MYSQL_PASSWORD=qickstudy
      - MYSQL_DATABASE=QickStudy
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - qick

  redis:
    image: redis:latest
    container_name: redis_db
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    networks:
      - qick

networks:
  qick:
    driver: bridge