version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8080
    depends_on:
      - mysql
      - redis
    restart: always
    environment:
      - FLASK_MODE=ProductionEnv

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data