"""empty message

Revision ID: 3567534a6585
Revises: 
Create Date: 2023-05-26 15:52:54.874738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3567534a6585'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Qc_Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('sinceTime', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Qc_Users_email'), 'Qc_Users', ['email'], unique=True)
    op.create_index(op.f('ix_Qc_Users_username'), 'Qc_Users', ['username'], unique=True)
    op.create_table('Qc_UserAttend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendDate', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Qc_UserAttend')
    op.drop_index(op.f('ix_Qc_Users_username'), table_name='Qc_Users')
    op.drop_index(op.f('ix_Qc_Users_email'), table_name='Qc_Users')
    op.drop_table('Qc_Users')
    # ### end Alembic commands ###
