"""empty message

<<<<<<<< Updated upstream:migrations/versions/27b08754825d_.py
Revision ID: 27b08754825d
Revises: 
Create Date: 2023-07-28 22:02:08.192763
========
Revision ID: dfdb4978b4f7
Revises: 
Create Date: 2023-08-01 20:00:48.503586
>>>>>>>> Stashed changes:migrations/versions/dfdb4978b4f7_.py

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
<<<<<<<< Updated upstream:migrations/versions/27b08754825d_.py
revision = '27b08754825d'
========
revision = 'dfdb4978b4f7'
>>>>>>>> Stashed changes:migrations/versions/dfdb4978b4f7_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Qc_Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('delFlag', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('logo', mysql.LONGTEXT(), nullable=True),
    sa.Column('sinceTime', sa.DateTime(), nullable=True),
    sa.Column('resetTime', sa.DateTime(), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_index(op.f('ix_Qc_Users_confirmed'), 'Qc_Users', ['confirmed'], unique=False)
    op.create_index(op.f('ix_Qc_Users_email'), 'Qc_Users', ['email'], unique=True)
    op.create_index(op.f('ix_Qc_Users_permission'), 'Qc_Users', ['permission'], unique=False)
    op.create_index(op.f('ix_Qc_Users_username'), 'Qc_Users', ['username'], unique=True)
    op.create_table('Qc_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventId', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=1000), nullable=False),
    sa.Column('nums', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Qc_logs_eventId'), 'Qc_logs', ['eventId'], unique=False)
    op.create_index(op.f('ix_Qc_logs_nums'), 'Qc_logs', ['nums'], unique=False)
    op.create_table('Qc_UserAttend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendDate', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Qc_UserInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('context', mysql.LONGTEXT(), nullable=False),
    sa.Column('lastTime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('agree', sa.Integer(), nullable=False),
    sa.Column('watch', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_table('follows',
    sa.Column('followerId', sa.Integer(), nullable=False),
    sa.Column('followTarget', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followTarget'], ['Qc_Users.id'], ),
    sa.ForeignKeyConstraint(['followerId'], ['Qc_Users.id'], ),
    sa.PrimaryKeyConstraint('followerId', 'followTarget')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_table('articles')
    op.drop_table('Qc_UserInfo')
    op.drop_table('Qc_UserAttend')
    op.drop_index(op.f('ix_Qc_logs_nums'), table_name='Qc_logs')
    op.drop_index(op.f('ix_Qc_logs_eventId'), table_name='Qc_logs')
    op.drop_table('Qc_logs')
    op.drop_index(op.f('ix_Qc_Users_username'), table_name='Qc_Users')
    op.drop_index(op.f('ix_Qc_Users_permission'), table_name='Qc_Users')
    op.drop_index(op.f('ix_Qc_Users_email'), table_name='Qc_Users')
    op.drop_index(op.f('ix_Qc_Users_confirmed'), table_name='Qc_Users')
    op.drop_table('Qc_Users')
    # ### end Alembic commands ###
